### ISSUE TITLE
`KeyError` when accessing `log_entry` in `qa_exec`

### ISSUE THREAD

**Issue by ufladrich** [IS-ENES-Data/QA-DKRZ#8]
Hi,
I'm in the process of applying `qa-dkrz` to EC-Earth CMIP6 output. By just setting `PROJECT_DATA`, `SELECT`, and `QA_RESULTS` in a configuration file `CMIP6_qa.conf` and running
```
> qa-dkrz -P CMIP6
```
I get the following error:
```python
Traceback (most recent call last):
  File "[...]/.conda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "[...]/.conda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "[...]/.conda/envs/qa-dkrz-new/opt/qa-dkrz/python/qa-dkrz/qa_launcher.py", line 77, in start
    if not self.run(data_path, fNames[ix], t_vars):
  File "[...]/.conda/envs/qa-dkrz-new/opt/qa-dkrz/python/qa-dkrz/qa_launcher.py", line 30, in run
    return self.qa_exec.run(t_vars)
  File "[...]/.conda/envs/qa-dkrz-new/opt/qa-dkrz/python/qa-dkrz/qa_exec.py", line 583, in run
    period      = log_entry['period'],
KeyError: 'period'
```
I got around the problem by adding an empty list as a default value for the `log_entry` dict in case the particular `period` does not exist. A similar problem occurred in this case with the `conclusion` key.
Fixing both issues in `qa_exec.py` I ended up with:
```diff
diff --git a/python/qa-dkrz/qa_exec.py b/python/qa-dkrz/qa_exec.py
index 4feea9f..969ea1b 100644
--- a/python/qa-dkrz/qa_exec.py
+++ b/python/qa-dkrz/qa_exec.py
@@ -580,8 +580,8 @@ class QaExec(object):
                                         f           = t_vars.fName,
                                         d_path      = t_vars.data_path,
                                         r_path      = t_vars.var_path,
-                                        period      = log_entry['period'],
-                                        conclusion  = log_entry['conclusion'],
+                                        period      = log_entry.get('period', []),
+                                        conclusion  = log_entry.get('conclusion', ''),
                                         set_qa_lock = set_qa_lock)
 
         if 'is_event' in log_entry:
```
However, I am not sure if that creates or hides a problem elsewhere.

**Comment by h-dh** [comment]
presumably solved by some coding in the context of another issue
